# from linked_list import LinkedList
# linked_list=LinkedList()
# linked_list.add_node(5)
# linked_list.add_node(7)
# linked_list.add_node(8)
# print(linked_list.find_node(18))
# print(linked_list.find_node(7))

from binary_node import TreeNode
root1=TreeNode()
root1.insert_node(root1.root,27)
root1.insert_node(root1.root,14)
root1.insert_node(root1.root,35)
root1.insert_node(root1.root,10)
root1.insert_node(root1.root,19)
root1.insert_node(root1.root,31)
root1.insert_node(root1.root,42)
# root1.insert_node(root1.root,50)
# root1.insert_node(root1.root,5)
# root1.insert_node(root1.root,6)
# root1.insert_node(root1.root,7)
# root1.insert_node(root1.root,8)
# root1.insert_node(root1.root,9)
# root1.insert_node(root1.root,1)
# root1.insert_node(root1.root,2)
# root1.insert_node(root1.root,3)
# root1.insert_node(root1.root,4)
# root1.insert_node(root1.root,11)
# root1.insert_node(root1.root,12)